# Generated by Django 4.2 on 2023-06-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "satisfaction",
                    models.CharField(
                        choices=[
                            ("very_satisfied", "Very Satisfied"),
                            ("satisfied", "Satisfied"),
                            ("neutral", "Neutral"),
                            ("dissatisfied", "Dissatisfied"),
                            ("very_dissatisfied", "Very Dissatisfied"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
