# Generated by Django 4.2 on 2023-06-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="voice",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="voice",
            name="end_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="voice",
            name="start_time",
            field=models.DateTimeField(null=True),
        ),
    ]
